export const seoRoutes = [
  {
    pathname: "/",
    output: "index.html",
    title: "Народный юрист — помощь при мошенничестве в Москве",
    description: "Помогаем вернуть деньги, похищенные мошенниками. Народный юрист в Москве: помощь при списаниях, переводах, кредитах и передаче денег или ценностей курьеру.",
    canonical: "https://pravonaroda.ru/",
    robots: "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
    socialImage: true,
    includeInSitemap: true,
    lastModified: "2026-08-30",
  },
  {
    pathname: "/pomoshch-pri-moshennichestve/",
    output: "pomoshch-pri-moshennichestve/index.html",
    title: "Помощь при мошенничестве: деньги, наличные и ценности | Народный юрист",
    description: "Что делать после хищения денег или ценностей, перевода мошенникам, незаконного списания или передачи курьеру. Юридическая помощь в Москве.",
    canonical: "https://pravonaroda.ru/pomoshch-pri-moshennichestve/",
    robots: "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
    socialImage: false,
    includeInSitemap: true,
    lastModified: "2026-08-30",
  },
  {
    pathname: "/politika-konfidencialnosti/",
    output: "politika-konfidencialnosti/index.html",
    title: "Политика конфиденциальности | Народный юрист",
    description: "Политика обработки персональных данных сайта «Народный юрист».",
    canonical: "https://pravonaroda.ru/politika-konfidencialnosti/",
    robots: "noindex, follow",
    socialImage: false,
    includeInSitemap: false,
    lastModified: "2026-08-30",
  },
];
